language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

os:
    - linux
    - osx
    - windows

# Since bionic is the most used Ubuntu distro, I used bionic here.
dist:
    - bionic

cache: pip

install:
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt

script:
    - python -m pytest
    - python -m flake8 ./
    - python -m black ./
